chat/urls.py
from django.urls import path

from .views import index, room

app_name = "chat"

urlpatterns = [
    path("", index, name="index"),
    path("room/<int:room_id>/", room, name="room"),
]

drf_channels_example/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("chat.urls")),
    path("admin/", admin.site.urls),
]

chat/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Room(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False, unique=True)
    host = models.ForeignKey(User, on_delete=models.CASCADE, related_name="rooms")
    current_users = models.ManyToManyField(User, related_name="current_rooms", blank=True)

    def __str__(self):
        return f"Room({self.name} {self.host})"


class Message(models.Model):
    room = models.ForeignKey("chat.Room", on_delete=models.CASCADE, related_name="messages")
    text = models.TextField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="messages")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message({self.user} {self.room})"

chat/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse

from .models import Room


def index(request):
    if request.method == "POST":
        name = request.POST.get("name", None)
        if name:
            room, _ = Room.objects.get_or_create(name=name)
            print(room)
            return HttpResponseRedirect(reverse("chat:room", args=(room.id,)))
    return render(request, "chat/index.html")


def room(request, room_id):
    room: Room = get_object_or_404(Room, id=room_id)
    return render(request, "chat/room.html", {"room": room})

chat/templates/chat/index.html
{% extends "chat/layout.html" %} {% block content %} What chat room would you
like to enter?
<br />
<form method="post" action="{% url 'chat:index' %}">
  {% csrf_token %}
  <input id="room-name-input" name="name" type="text" size="100" />
  <br />
  <input id="room-name-submit" type="submit" value="Enter" />
</form>
{% endblock content %}

chat/templates/chat/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Django Rest Framework Channels" />
    <meta name="keywords" content="Django, Rest, Framework, Channels" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DRF Channels</title>
  </head>
  <body>
    {% block content %} {% endblock content %} {% block footer %} {% endblock
    footer %}
  </body>
</html>

chat/templates/chat/room.html
{% extends "chat/layout.html" %} {% load static %} {% block content %}
<textarea id="chat-log" cols="100" rows="20"></textarea>
<br />
<input id="chat-message-input" type="text" size="100" />
<br />
<input id="chat-message-submit" type="button" value="Send" />
{% endblock content %} {% block footer %}
<script>
  const room_pk = '{{ room.pk }}';
  const request_id = '{{ request.sessions.session_key }}';
  console.log(request_id);

  const chatSocket = new WebSocket(
    `ws://${window.location.host}/ws/chat/room/`,
  );

  chatSocket.onopen = function () {
    chatSocket.send(
      JSON.stringify({
        pk: room_pk,
        action: 'join_room',
        request_id: request_id,
      }),
    );
    chatSocket.send(
      JSON.stringify({
        pk: room_pk,
        action: 'retrieve',
        request_id: request_id,
      }),
    );
    chatSocket.send(
      JSON.stringify({
        pk: room_pk,
        action: 'subscribe_to_messages_in_room',
        request_id: request_id,
      }),
    );
    chatSocket.send(
      JSON.stringify({
        pk: room_pk,
        action: 'subscribe_instance',
        request_id: request_id,
      }),
    );
  };

  chatSocket.onmessage = function (e) {
    const data = JSON.parse(e.data);
    switch (data.action) {
      case 'retrieve':
        setRoom((old) => data.data);
        setMessages((old) => data.messages);
        break;
      case 'create':
        setMessages((old) => [...old, data]);
        break;
      default:
        break;
    }
    // Remove the unnecessary break statement
    // break;
  };

  chatSocket.onclose = function (e) {
    console.error('Chat socket closed unexpectedly');
  };

  $('#chat-message-input').focus();
  $('#chat-message-input').on('keyup', function (e) {
    if (e.keyCode === 13) {
      // enter, return
      document.querySelector('#chat-message-submit').click();
    }
  });

  $('#chat-message-submit').on('click', function (e) {
    const message = $('#chat-message-input').val();
    chatSocket.send(
      JSON.stringify({
        message: message,
        action: 'create_message',
        request_id: request_id,
      }),
    );
    $('#chat-message-input').val('');
  });
</script>
{% endblock footer %}